### ISSUE TITLE
when running vitest(using react-testing-library-dom) in git action, action exceeded the maximum execution time of xx minutes

### ISSUE THREAD

**Issue by JayKim88** [testing-library/dom-testing-library#1299]
- `@testing-library/dom` version: ^9.3.1
- Testing Framework and version: vitest,  1.3.0
  
- DOM Environment: jsdom ^22.1.0
  

### Relevant code or config:

```ts
// error occurs in a code using synchronous method to find an element.
it('~~~~', () => {
...
 await userEvent.click(totalCheckBoxInTable); // this makes changes in UI

const combineBtn = screen.getAllByText('합포장')[0]; // here, cannot find element in git action ending up with spending whole testing time with fail.
...
})
```
### What you did:

In git action, it fails with the comment as
"The job running on runner GitHub Actions XX has exceeded the maximum execution time of XX minutes."

As shown in the reproduction image, after combineOrders.test.tsx is passed, and it is stuck in the next test spending the whole test time ending up with test fail.

After testing this, I found that this error occurs in case that test tries to find a element by synchronous method such as getByText, getBy-. In local environment, it occurs error as intended if not found.
If I replace these methods with asynchronous method like findby-, it works well locally and in git action.

### What happened:

<img src="https://github.com/testing-library/dom-testing-library/assets/55373668/c6d6626f-93f6-4a96-aef8-3b216e641771" alt="git-action-error-image">

### Problem description:

Explained in What you did.

### Suggested solution:

I haven't found a solution for it. 
Are there anybody who experienced this case ?
I hope to know why this happens and how to fix it accordingly. 
I expect it must make error and fail as soon as it's impossible to find a target element.

Thank you all !

(By any chance, if it should be posted as Support Question, please let me know🙏)

**Comment by MatanBobi** [comment]
Hi @JayKim88, thanks for opening this.
Unfortunately this issue doesn't have enough for us to start investigating. Usually, `getAllBy` queries throw an error when elements can't be found so I highly don't think that's the command causing the issue.

Can you please share a minimal reproduction of this issue using our [template](https://testing-library.com/new-dtl)?

Thanks.

**Comment by JayKim88** [comment]
@MatanBobi Thank you for your reply. The error takes place in git action when i try to push a PR(But locally, it works well.), thus, by using the template as you kindly suggested, can I make reproduction of git action as well? Or is it enough for you to get a part of codes like below? also i'm able to provide you with a short video showing the error.
```yml
...
on:
  pull_request:
    branches:
      - staging
...
jobs:
            check_and_test:
              timeout-minutes: 10
              runs-on: ubuntu-latest
              steps:
                ...
                - name: Codegen and check type and test code
                  run: |
                    export NODE_OPTIONS="--max-old-space-size=4096"
                    pnpm i --frozen-lockfile
                    pnpm tsc --noEmit
                    pnpm test run // this is 
                    pnpm codegen
```

Thank you..!
